### ISSUE TITLE
Some Gmail notifications are not sent to the watch. 

### ISSUE THREAD

**Issue by GrinFactor** [AmazMod/AmazMod#243]
I find that not all of my Gmail messages show on the watch. Most come through on the watch but about 20%+ do not. 

I'm not using the service apk and only have Amazmod installed as I do not care about replying from the watch.

Any Idea's as to why not all gmail messages gets sent to the watch?

**Comment by Raspel16278** [comment]
I have installed service app with the same problem.

**Comment by edotassi** [comment]
do you have any more information? Can you register a logcat while receiving an email?

**Comment by Raspel16278** [comment]
I tried:

--------- beginning of main
10-22 16:53:12.308 I/zygote64(9377): Reinit property: dalvik.vm.checkjni= false
--------- beginning of system
10-22 16:53:12.320 D/ActivityThread(9377): ActivityThread,attachApplication
10-22 16:53:12.460 D/HwFLClassLoader(9377): get used feature list :/feature/used-list failed!
10-22 16:53:12.460 D/HwFLClassLoader(9377): USE_FEATURE_LIST had not init! 
10-22 16:53:12.504 E/MemoryLeakMonitorManager(9377): MemoryLeakMonitor.jar is not exist!
10-22 16:53:12.506 E/Minikin (9377): Could not get cmap table size!
10-22 16:53:12.530 I/HwCust  (9377): Constructor found for class android.app.HwCustActivityImpl
10-22 16:53:12.530 D/HwCust  (9377): Create obj success use class android.app.HwCustActivityImpl
10-22 16:53:12.538 V/HwPolicyFactory(9377): : success to get AllImpl object and return....
10-22 16:53:12.544 I/HwCust  (9377): Constructor found for class android.app.HwCustHwWallpaperManagerImpl
10-22 16:53:12.544 D/HwCust  (9377): Create obj success use class android.app.HwCustHwWallpaperManagerImpl
10-22 16:53:12.549 V/ActivityThread(9377): ActivityThread,callActivityOnCreate
10-22 16:53:12.556 V/HwWidgetFactory(9377): : successes to get AllImpl object and return....
10-22 16:53:12.583 W/Utils   (9377): Utils_isSuperResolutionSupport [load libai_client.so failed]
10-22 16:53:12.596 D/HwGalleryCacheManagerImpl(9377): mIsEffect:false
10-22 16:53:12.754 D/HwWechatOptimizeImpl(9377): mIsEffect:false
10-22 16:53:12.775 D/HwRTBlurUtils(9377): check blur style for HwPhoneWindow, themeResId : 0x01030005, context : com.nolanlawson.logcat.LogcatActivity@30176d7, Nhwext : 0, get Blur : disable with , null
10-22 16:53:12.843 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
10-22 16:53:12.843 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
10-22 16:53:12.843 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
10-22 16:53:12.844 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
10-22 16:53:12.868 D/HwRTBlurUtils(9377): check blur style for HwPhoneWindow, themeResId : 0x010303cb, context : android.view.ContextThemeWrapper@3afb3c6, Nhwext : 0, get Blur : disable with , null
10-22 16:53:12.874 I/HwSecImmHelper(9377): mSecurityInputMethodService is null
10-22 16:53:12.890 D/ActivityThread(9377): add activity client record, r= ActivityRecord{a9e1d23 token=android.os.BinderProxy@8a5e618 {com.nolanlawson.logcat/com.nolanlawson.logcat.LogcatActivity}} token= android.os.BinderProxy@8a5e618
10-22 16:53:12.892 W/Settings(9377): mValues not put! needsGenerationTracker: true currentGeneration: -1 name: enable_navbar value: null
10-22 16:53:12.897 W/m       (9377): Cannot obtain root
10-22 16:53:12.897 W/m       (9377): java.io.IOException: Cannot run program "su": error=13, Permission denied
10-22 16:53:12.897 W/m       (9377): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
10-22 16:53:12.897 W/m       (9377): 	at java.lang.Runtime.exec(Runtime.java:692)
10-22 16:53:12.897 W/m       (9377): 	at java.lang.Runtime.exec(Runtime.java:525)
10-22 16:53:12.897 W/m       (9377): 	at java.lang.Runtime.exec(Runtime.java:422)
10-22 16:53:12.897 W/m       (9377): 	at com.nolanlawson.logcat.b.m.a(Unknown Source:17)
10-22 16:53:12.897 W/m       (9377): 	at com.nolanlawson.logcat.b.w.a(Unknown Source:2)
10-22 16:53:12.897 W/m       (9377): 	at com.nolanlawson.logcat.b.p.b(Unknown Source:32)
10-22 16:53:12.897 W/m       (9377): 	at com.nolanlawson.logcat.d.doInBackground(Unknown Source:2)
10-22 16:53:12.897 W/m       (9377): 	at android.os.AsyncTask$2.call(AsyncTask.java:345)
10-22 16:53:12.897 W/m       (9377): 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
10-22 16:53:12.897 W/m       (9377): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
10-22 16:53:12.897 W/m       (9377): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
10-22 16:53:12.897 W/m       (9377): 	at java.lang.Thread.run(Thread.java:784)
10-22 16:53:12.897 W/m       (9377): Caused by: java.io.IOException: error=13, Permission denied
10-22 16:53:12.897 W/m       (9377): 	at java.lang.UNIXProcess.forkAndExec(Native Method)
10-22 16:53:12.897 W/m       (9377): 	at java.lang.UNIXProcess.<init>(UNIXProcess.java:133)
10-22 16:53:12.897 W/m       (9377): 	at java.lang.ProcessImpl.start(ProcessImpl.java:128)
10-22 16:53:12.897 W/m       (9377): 	at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
10-22 16:53:12.897 W/m       (9377): 	... 12 more
10-22 16:53:12.909 I/PressGestureDetector(9377): HiTouch restricted: AboardArea.
10-22 16:53:12.964 I/PressGestureDetector(9377): HiTouch restricted: AboardArea.
10-22 16:53:12.996 D/HwRTBlurUtils(9377): check blur style for HwToast-Toast, themeResId : 0x01030005, context : com.nolanlawson.logcat.LogcatActivity@30176d7, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@f0c5c68
10-22 16:53:13.051 D/HwRTBlurUtils(9377): check blur style for HwToast-Toast, themeResId : 0x01030005, context : com.nolanlawson.logcat.LogcatActivity@30176d7, Nhwext : 6, get Blur : disable with , android.graphics.drawable.NinePatchDrawable@d65dd67
10-22 16:53:13.168 W/InputMethodManager(9377): startInputReason = 1
10-22 16:53:13.204 W/ViewRootImpl[Toast](9377): EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.nolanlawson.logcat) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0xbe4e90a,viewVisibility is0
10-22 16:53:13.228 W/ViewRootImpl[Toast](9377): EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.nolanlawson.logcat) ( mSurfaceControllerIsValid =true) (mNativeObject  =7cd1890000)/@0xbe4e90a,relayoutResult is7
10-22 16:53:13.229 W/InputMethodManager(9377): startInputReason = 5
10-22 16:53:15.600 D/KeyEvent(9377): obtain, mHwFlags=0
10-22 16:53:15.877 D/KeyEvent(9377): obtain, mHwFlags=0
10-22 16:53:16.012 I/zygote64(9377): Do partial code cache collection, code=30KB, data=24KB
10-22 16:53:16.013 I/zygote64(9377): After code cache collection, code=30KB, data=24KB
10-22 16:53:16.013 I/zygote64(9377): Increasing code cache capacity to 128KB
10-22 16:53:16.022 V/AudioManager(9377): playSoundEffect   effectType: 0
10-22 16:53:16.025 I/PressGestureDetector(9377): HiTouch restricted: AboardArea.
10-22 16:53:16.598 W/ViewRootImpl[Toast](9377): EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.nolanlawson.logcat) ( mSurfaceControllerIsValid =false) (mNativeObject  =0)/@0x90639c1,viewVisibility is0
10-22 16:53:16.616 W/ViewRootImpl[Toast](9377): EGLdebug relayoutWindow Surface isSurface(name=null)  (appName =com.nolanlawson.logcat) ( mSurfaceControllerIsValid =true) (mNativeObject  =7cd1890000)/@0x90639c1,relayoutResult is7
10-22 16:53:17.107 E/Input   (9377): getAxisValue(): y-1693.0--2008.0--315.0
10-22 16:53:17.110 E/Input   (9377): getAxisValue(): y-1693.0--2008.0--315.0
10-22 16:53:17.120 I/hwaps   (9377): JNI_OnLoad
10-22 16:53:17.240 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
10-22 16:53:17.240 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
10-22 16:53:17.241 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.23, mControlPoint1y = 0.06, mControlPoint2x = 0.09, mControlPoint2y = 0.97
10-22 16:53:17.241 D/CubicBezierInterpolator(9377): CubicBezierInterpolator  mControlPoint1x = 0.6, mControlPoint1y = 0.9, mControlPoint2x = 0.8, mControlPoint2y = 1.0
10-22 16:53:17.250 D/HwRTBlurUtils(9377): check blur style for HwPhoneWindow, themeResId : 0x010303cb, context : android.view.ContextThemeWrapper@4e1aff0, Nhwext : 0, get Blur : disable with , null
10-22 16:53:17.262 V/AudioManager(9377): playSoundEffect   effectType: 0
10-22 16:53:17.268 I/PressGestureDetector(9377): HiTouch restricted: AboardArea.
10-22 16:53:17.372 W/InputMethodManager(9377): startInputReason = 1
10-22 16:53:17.428 W/View    (9377): dispatchProvideAutofillStructure(): not laid out, ignoring
10-22 16:53:17.430 I/chatty  (9377): uid=10182(u0_a182) com.nolanlawson.logcat identical 58 lines
10-22 16:53:17.430 W/View    (9377): dispatchProvideAutofillStructure(): not laid out, ignoring
10-22 16:53:17.441 I/AssistStructure(9377): Flattened final assist data: 32688 bytes, containing 3 windows, 171 views

**Comment by lfom** [comment]
@Raspel16278 logcat from phone, please filter for "amazmod" for the time you get the notifications on on phone, also please add a screenshot of the notifications log from AmazMod app.

**Comment by edotassi** [comment]
is there any news?

**Comment by lfom** [comment]
@Raspel16278 Try MatLog app from PlayStore (free), filter for "amazmod", also attach a screenshot of notifications log showing Gmail.

**Comment by Raspel16278** [comment]
See.
![screenshot_20181113-134032](https://user-images.githubusercontent.com/33427333/48414172-3950e880-e74a-11e8-92e5-1efeaeb8f3ef.jpg)
![screenshot_20181113-134044](https://user-images.githubusercontent.com/33427333/48414175-3bb34280-e74a-11e8-9ee4-0b6825ff7acf.jpg)

**Comment by diotto** [comment]
@Raspel16278 how are your notifications in version 1.1.3 + service 1880 ? Is everything ok now ?

**Comment by Raspel16278** [comment]
Hello,
I've been testing it for the past two weeks. Gmail is now just like all
other - Stratos recied notification when the display lights up (manually),
or after about 10 minutes (without touch). All notifications will come all
but not immediately after receiving. I'm beginning to worry that Huawei may
be all for it.

ut 12. 2. 2019 o 17:51 Marcelo Diotto <notifications@github.com> napísal(a):

**Comment by GreatApo** [comment]
@Raspel16278 How are your notifications in version version 1.1.5 + service 1891? Was there a difference?

**Comment by Raspel16278** [comment]
Horible. Aprox 20min late with tephone in my pocket.

Dne st 10. dub 2019 15:32 uživatel Grammatopoulos Apostolos <
notifications@github.com> napsal:

**Comment by fcaronte** [comment]
try to see battery optimization here for amazfit app and amazmod app too
1. App info -> Battery -> Manage manually and enable all 3 options (enabled by default);
2. Settings -> Apps -> Settings -> Special Access -> Ignore optimizations and enable it for Amazfit and AmazMod

**Comment by Raspel16278** [comment]
Done (like before) without succes.

ut 16. 4. 2019 o 0:07 fcaronte <notifications@github.com> napísal(a):

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Bugs](https://trello.com/c/9ugXmoGc/1-bugs)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Some Gmail notifications are not sent to the watch.](https://trello.com/c/GawmeIyQ/12-some-gmail-notifications-are-not-sent-to-the-watch)

**Comment by fcaronte** [comment]
Any news here? I think can be closed

**Comment by Raspel16278** [comment]
For me yes - due to many problems I changed brand.

Dňa ne 8. 9. 2019, 8:41 fcaronte <notifications@github.com> napísal(a):
