### ISSUE TITLE
Messenger notifications not working

### ISSUE THREAD

**Issue by jandrabek** [AmazMod/AmazMod#301]
I have latest version of Amazmod and services. I have Xiaomi MiA2. My notifications are working for most of the apps but no messenger. Classic amazfit app push notifications are disabled. Any suggestions?

**Comment by Veligord** [comment]
I have phone Xiaomi MiA2 Lite and I have notifications from messengers (check on whatsApp and FB Messenger). 
You need to check that you have enabled notifications in the messengers themselves, otherwise they will not come to the watch. I myself did not receive notifications from the FB Messenger until I enabled notifications for him in app settings. Before that, they were completely disabled. After this notifications began to come.

**Comment by jandrabek** [comment]
I have it enabled. I suppose when I get notification on the phone I should get it also on my watch.

**Comment by jandrabek** [comment]
Just tested Messenger Lite and is working correctly. There is problem with classic Messenger. Every notification is on but not working. Not sure why.

**Comment by Veligord** [comment]
oddly, because I just checked on the standard FB Messenger and I have notifications from messenger

**Comment by edotassi** [comment]
@jandrabek @Veligord so the notifications arrive yes or no?

**Comment by Veligord** [comment]
I have come all notices, including messendgers. And **jandrabek** not getting notifications from messengers, and the other receives.

**Comment by jandrabek** [comment]
In log every message is displayed. Sometimes SCREENON sometimes LOCAL sometimes ONGOING but it never shows on the watch.

**Comment by GreatApo** [comment]
There will be a release the following days, if the problem persists please re-open the bug.
