### ISSUE TITLE
[MIUI] Replying for SMS doesnt't work

### ISSUE THREAD

**Issue by the4anoni** [AmazMod/AmazMod#328]
My phone is redmi note 5 with miui 10 stable 10.0.4.0. All persmissions are granted.
AmazMod Play Store version and Latest services on watch

**Comment by lfom** [comment]
Some apps, specially built-in SMS ones, do not allow replies by third party sources as a security reason or simply doesn't allow replies by the current method using in the release version (via WearableExtensions). This may get improved in the next version. If it still doesn't work for you, the only option is using a third party SMS app, it cannot be fixed by AmazMod itself.

**Comment by the4anoni** [comment]
But why we can't implement sending sms from Amazmod ?

**Comment by lfom** [comment]
Because the app does not support replies from the notifications in a way the other apps can interact with it, it's a limitation from the SMS app, no AmazMod...
