### ISSUE TITLE
Notifications after disabling airplane mode

### ISSUE THREAD

**Issue by ajeje93** [AmazMod/AmazMod#399]
I have automatic airplane mode set from 22.00 to 7.30.
When the airplane mode automatically disables at 7.30, I receive all the notifications, even the ones that i dismissed on the phone during airplane mode.
My phone is a Redmi Note 4 and my watch an Amazfit Pace.
On the watch I have installed the service 1880 and on the phone the app 1.1.3.

**Comment by Kookie69** [comment]
Yes i have a S7 and my watch does exactly the same thing when you turn off airplane mode the messages just flood the watch 1 after another so i'm thinking Amazmod must back up the messages and send them once it's reconnected.

**Comment by diotto** [comment]
This is expected behavior after the implementation of JobScheduler. Lots of users are having issues with disconnections with Samsung phones (not related to amazmod, its about oficial app + watch) and were losing notifications. Amazmod implemented a Scheduler which keeps notifications in a queue and, when watch reconnects it sends all of them to you. 
This Scheduler caused this issue. We are working on a way to disable the scheduler (for those which are not having disconnection issues) or define a max time (for example: if watch is disconnected for more than 30 minutes, notifications wont be forwarded to watch when it connects back)

**Comment by diotto** [comment]
I'm closing this issue, as it is being addressed in #339
