### ISSUE TITLE
How to uninstall amazmod service

### ISSUE THREAD

**Issue by gautamkrishnar** [AmazMod/AmazMod#438]
I tried to uninstall the service, it is not possible because the app is set as device admin. How can i remove the app from device admin?

I tried revoke admin option but no luck....

**Comment by gautamkrishnar** [comment]
```bash
Mac:platform-tools gautamkrishnar$ ./adb uninstall com.amazmod.service
Failure [DELETE_FAILED_DEVICE_POLICY_MANAGER]
```

**Comment by diotto** [comment]
Hello @gautamkrishnar . Previous versions of amazmod were using device owner instead of device admin. We changed it in last release but, if you didn't revoked device owner before upgrading, now you can't revoke it.
If it's the case only solution will be factory resetting watch. Easiest way is unpairing/pairing again watch.

**Comment by gautamkrishnar** [comment]
Finally i did it... I used the old version of the app: https://github.com/AmazMod/AmazMod/releases/download/1702/AmazMod-service-1702.apk

installed it using:
```
adb install -r -d AmazMod-service-1702.apk 
```
Selected the option to remove device admin in the app by pressing and holding on the logo in the widget.

Removed app using adb:
```
adb uninstall com.amazfit.service
```

It worked.. No reset is required... Hope this help someone who has this issue in the future...
