### ISSUE TITLE
GPS ON/OFF Switch #enhancement

### ISSUE THREAD

**Issue by dibg** [AmazMod/AmazMod#439]
When i use a app like offline maps the gps, or gps speedometer seems to stay active even after closing the application since the battery depletes in a faster rate. Amazmod is a essential application in my watch and having a option to close the gps will have begin really  convenient. Right now i have to restart the watch every time i use a app which does that.

**Comment by lfom** [comment]
GPS is always active on watch, you can check this using this adb command (if it does not show "gps" then it would be off, but it is never something other than "gps"):

`adb shell settings get secure location_providers_allowed`

Probably the map app you are using is draining battery because you didn't close/quit the app properly. AmazMod already has a feature to kill background.
