### ISSUE TITLE
Reorder widgets - Phone app

### ISSUE THREAD

**Issue by GreatApo** [AmazMod/AmazMod#472]
Ability to reorder widgets from the phone app.
Details:
- New "Widgets" app menu item
- Move the "Amazmod 1st widget" option in this menu
- New option to force apply this widget setup (monitor system's variable and if amazfit changes it, reapply the saved data)
- Request widgets from phone, show them and then reorder them
- Add ability to read new widgets and not only show those saved in the system variable

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Reorder widgets - Phone app](https://trello.com/c/CJ7T9ykt/27-reorder-widgets-phone-app)

**Comment by ransit** [comment]
Hi Dears,
İ tried to use reorder widgets. But aplications frequently crashes. For examle i am chosing weather as widget, after a while it stops. And some apps(Peace Calender app, timeline app) not shown on aplication list. Sometimes they shown. İs there any way to solve this problem.

**Comment by GreatApo** [comment]
The apps not showing is related to the way apps are registered in the system launchers variable. Just reboot the watch or the launcher until they are shown.

For the crash we will need a log if you can pull it :)

It is noted that this issue is related to the phone side feature that is not scripted yet.

**Comment by ransit** [comment]
Thaks for your answer,
Here is my log.


Samsung Galaxy akıllı telefonumdan gönderildi.


-------- Orijinal mesaj --------
Başlangıç tarihi: Grammatopoulos Apostolos <notifications@github.com>
Tarih: 12.08.2019 19:58 (GMT+03:00)
Alıcı: AmazMod/AmazMod <AmazMod@noreply.github.com>
Cc: ransit <tolga_uskutoglu@hotmail.com>, Comment <comment@noreply.github.com>
Konu: Re: [AmazMod/AmazMod] Reorder widgets - Phone app (#472)


The apps not showing is related to the way apps are registered in the system launchers variable. Just reboot the watch or the launcher until they are shown.

For the crash we will need a log if you can pull it :)

It is noted that this issue is related to the phone side feature that is not scripted yet.

**Comment by elaijha777** [comment]
Hi thank i resolve this problem.

**Comment by ransit** [comment]
Thanks for you dor your efford. İ send the logs.

**Comment by ransit** [comment]
Samsung Galaxy akıllı telefonumdan gönderildi.


-------- Orijinal mesaj --------
Başlangıç tarihi: elaijha777 <notifications@github.com>
Tarih: 12.08.2019 20:24 (GMT+03:00)
Alıcı: AmazMod/AmazMod <AmazMod@noreply.github.com>
Cc: ransit <tolga_uskutoglu@hotmail.com>, Comment <comment@noreply.github.com>
Konu: Re: [AmazMod/AmazMod] Reorder widgets - Phone app (#472)

Hi thank i resolve this problem.

**Comment by elaijha777** [comment]
AmazMod Phone Logs

**Comment by GreatApo** [comment]
Widgets can now be arranged from the phone.
Commit b7b604586ff610c0c966507bc157c90246aa5bae
Commit 2322be8346a596fe9ab12dc0cd2e31b079abcae1
Commit 843b7926970e72553da8722b81458a65f2b2454a

**Comment by ransit** [comment]
Thanks for all my friend. Pleased for your efford and kindness.

Android için Outlook<https://aka.ms/ghei36>'u edinin

________________________________
