### ISSUE TITLE
Re-design widget layout

### ISSUE THREAD

**Issue by alexagr** [AmazMod/AmazMod#474]
Notifications icon in the current AmazMod widget (1891) is rather small and placed in the right corner of the screen. This makes clicking on it rather tricky - at least I often miss it and need to do multiple clicks to open the custom notifications "drawer". 
I'd suggest to re-arrange the widget layout so that the icon is made larger and placed in the center of the screen - thus simplifying interaction with it. Alternatively you could split the widget into two separate screens - one for the notifications and another one for the rest of "goodies".

**Comment by GreatApo** [comment]
I also feel that we need to redesign the widget utilizing up/down swipes, because the screen is small and it it not easy to touch the current buttons.

My idea is:
- swipe down to see WiFi, Bluetooth and other settings buttons, apps maybe
- swipe up to see notifications

I worked on a preview (based on WearOS UI)  for guidance and feedback:
![12-1](https://user-images.githubusercontent.com/9620510/55731146-9909a200-5a11-11e9-86aa-0aa06e72d768.jpg)

**Comment by antares10** [comment]
I would really like to see this enhancement!

**Comment by Galwayguy** [comment]
This would be a welcome improvement.  I often send the wrong custom replies with occasional funny results.

**Comment by Galwayguy** [comment]
Also can you have a way to lock the widget so that accidental swipes don't remove items ?

**Comment by GreatApo** [comment]
I suppose you refer to the apps shortcuts in the apps scroll area. From my stand point, this feature is useless assuming that apk watchfaces are filtered and not shown as shortcuts (but visible in the apps menu).

**Comment by Galwayguy** [comment]
Sorry but I don't understand.  I find the scroll area very useful as I would have to go to the end of the watch to get to installed apps.

**Comment by GreatApo** [comment]
The swipe to remove is useless if the watchfaces are not shown by default.

**Comment by fcaronte** [comment]
Probably if we can filter better watchface we can remove the hide feature because append to much time to unwanted hide

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Features](https://trello.com/c/p6NGIJCP/2-features)

**Comment by 1immortal** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Re-design widget layout](https://trello.com/c/PQbBa0pQ/28-re-design-widget-layout)

**Comment by JanHavel** [comment]
I just wanted to post new issue, but found this thread..
 
Enhancement: I want notification button bigger in AM widget. It is hard to focus my finger on it.

**Comment by fcaronte** [comment]
About enhancement the problem with the overlay button is will stay always visible on all the watch page and is enabled only on clock screen, if me make it bigger them will have problem to use other things because that part of the screen is unusable
Flashlight have just is menu inside the app but if Good to have as first option widget, and I see no problem to open notification with a big finger too, probably is only need training to how to touch and then you will open always at first try
