### ISSUE TITLE
Notification delay 15-30 seconds.

### ISSUE THREAD

**Issue by Pigonson** [AmazMod/AmazMod#933]
Hello, 

Im useing stratos 3 and Huawei p30 pro. Notifications are delayed up to a minute. Chaning settings on the app doesnt change the delay much (if i dont time it its barely noticable). 
Am i missing something that would explain the delay?

**Comment by 1immortal** [comment]
Hi,

Stratos 3 support is not fully implemented, and the delay caused by the BLE protocol implemented in the S3 watch.
With some devices the delay can be a short one, few seconds, with some devices it can go up to a minute, sometimes even more.
At the current state, with the latest build, without the source code of Zepp/Amazfit app, this is as good as it gets with the S3 watch.
You can strip down everything from the notifications, graphics, images, and everything that is being used for the notifications, and the delay will be a little shorter.
